### ISSUE TITLE
Enable macro annotation

### ISSUE THREAD

**Issue by Atry** [ochrons/scalafiddle-core#5]
[Binding.scala](https://github.com/ThoughtWorksInc/Binding.scala)'s `@dom` annotation requires macro paradise plugin. I wonder if it is possible to enable that compiler plugin.

**Comment by ochrons** [comment]
Yeah, this is probably useful for several other libraries as well. I'll see how it can be added.

**Comment by ochrons** [comment]
Fixed in https://github.com/ochrons/scalafiddle-core/commit/ca52da929242600b2a0898838c944586c8ea93ae
